version: '3.8'

services:
  redirectmanager:
    container_name: redirectmanager
    image: redirectmanager:latest
    ports:
      - "80:3000"
    environment:
      PORT: 3000
      BEARER_TOKEN: b2aee4d4-4087-453d-b915-78b612a2a238
    
    restart: unless-stopped